import Head from 'next/head';
import React, { useEffect } from 'react';
import styles from "../styles/modules/front.module.css";
import Header from '@/components/header';

export default function Home() {
  async function getStats() {
    try {
      const res = fetch("http://localhost:1000/api/launches");
      const data = await res.json();
    } catch (error) {
      console.error(error);
      throw error;
    }
  }

  return (
    <>
      <Head>
        <title>Launchpad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        <div className="site-content">
          <h3>Next up</h3>
          <div className={styles.item}>
            <p className={styles.subtext}>LC-39A</p>
            <h3 className={styles.heading}>SpaceX Falcon 9</h3>
            <p className={styles.subtext}>April 26, 2023</p>
          </div>
          <div className={styles.item}>
            <p className={styles.subtext}>LC-39A</p>
            <h3 className={styles.heading}>SpaceX Falcon 9</h3>
            <p className={styles.subtext}>April 26, 2023</p>
          </div>

          <div className={styles.item}>
            <p className={styles.subtext}>LC-39A</p>
            <h3 className={styles.heading}>SpaceX Falcon 9</h3>
            <p className={styles.subtext}>April 26, 2023</p>
          </div>
        </div>
      </div>
    </>
  );
}
